export interface VehicleBrand {
  id: string;
  name: string;
  logo?: string;
}

export interface VehicleModel {
  id: string;
  name: string;
  nameEn?: string;
}

/**
 * Common vehicle brands on the German market, sorted alphabetically.
 * Logo URLs point to Wikimedia Commons SVG/PNG assets.
 */
export const VEHICLE_BRANDS: VehicleBrand[] = [
  { id: "alfaromeo", name: "Alfa Romeo", logo: "https://upload.wikimedia.org/wikipedia/de/thumb/d/d3/Alfa_Romeo_2015.svg/200px-Alfa_Romeo_2015.svg.png" },
  { id: "audi", name: "Audi", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/200px-Audi-Logo_2016.svg.png" },
  { id: "bmw", name: "BMW", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/200px-BMW.svg.png" },
  { id: "citroen", name: "Citroën", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Citro%C3%ABn_2022.svg/200px-Citro%C3%ABn_2022.svg.png" },
  { id: "cupra", name: "CUPRA", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Cupra_logo.svg/200px-Cupra_logo.svg.png" },
  { id: "dacia", name: "Dacia", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Dacia_2021.svg/200px-Dacia_2021.svg.png" },
  { id: "fiat", name: "Fiat", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Fiat_Automobiles_logo.svg/200px-Fiat_Automobiles_logo.svg.png" },
  { id: "ford", name: "Ford", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Ford_logo_flat.svg/200px-Ford_logo_flat.svg.png" },
  { id: "honda", name: "Honda", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Honda.svg/200px-Honda.svg.png" },
  { id: "hyundai", name: "Hyundai", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Hyundai_Motor_Company_logo.svg/200px-Hyundai_Motor_Company_logo.svg.png" },
  { id: "jeep", name: "Jeep", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Jeep_logo.svg/200px-Jeep_logo.svg.png" },
  { id: "kia", name: "Kia", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Kia-logo.svg/200px-Kia-logo.svg.png" },
  { id: "landrover", name: "Land Rover", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c8/Land_Rover_logo2.svg/200px-Land_Rover_logo2.svg.png" },
  { id: "mazda", name: "Mazda", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Mazda_Motor_logo.svg/200px-Mazda_Motor_logo.svg.png" },
  { id: "mercedes", name: "Mercedes-Benz", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/200px-Mercedes-Logo.svg.png" },
  { id: "mg", name: "MG", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/MG_Motor_2021.svg/200px-MG_Motor_2021.svg.png" },
  { id: "mini", name: "MINI", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mini_logo_2023.svg/200px-Mini_logo_2023.svg.png" },
  { id: "nissan", name: "Nissan", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Nissan_2020_logo.svg/200px-Nissan_2020_logo.svg.png" },
  { id: "opel", name: "Opel", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Opel_logo_2024.svg/200px-Opel_logo_2024.svg.png" },
  { id: "peugeot", name: "Peugeot", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Peugeot_2021.svg/200px-Peugeot_2021.svg.png" },
  { id: "polestar", name: "Polestar", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Polestar_logo.svg/200px-Polestar_logo.svg.png" },
  { id: "porsche", name: "Porsche", logo: "https://upload.wikimedia.org/wikipedia/de/thumb/6/60/Porsche_Logo.svg/200px-Porsche_Logo.svg.png" },
  { id: "renault", name: "Renault", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Renault_2021.svg/200px-Renault_2021.svg.png" },
  { id: "seat", name: "SEAT", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Seat_Logo_2021.svg/200px-Seat_Logo_2021.svg.png" },
  { id: "skoda", name: "Škoda", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Skoda_2022.svg/200px-Skoda_2022.svg.png" },
  { id: "smart", name: "smart", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Smart_Automobile_Logo.svg/200px-Smart_Automobile_Logo.svg.png" },
  { id: "suzuki", name: "Suzuki", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Suzuki_logo_2.svg/200px-Suzuki_logo_2.svg.png" },
  { id: "tesla", name: "Tesla", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/200px-Tesla_Motors.svg.png" },
  { id: "toyota", name: "Toyota", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Toyota.svg/200px-Toyota.svg.png" },
  { id: "volvo", name: "Volvo", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Volvo_Cars_logo.svg/200px-Volvo_Cars_logo.svg.png" },
  { id: "vw", name: "Volkswagen", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Volkswagen_logo_2019.svg/200px-Volkswagen_logo_2019.svg.png" },
];

/**
 * Real models per brand (German market, 2020-2026 focus).
 * Keys match VehicleBrand.id. Models sorted alphabetically.
 */
export const VEHICLE_MODELS: Record<string, VehicleModel[]> = {
  alfaromeo: [
    { id: "giulia", name: "Giulia" },
    { id: "giulietta", name: "Giulietta" },
    { id: "junior", name: "Junior" },
    { id: "stelvio", name: "Stelvio" },
    { id: "tonale", name: "Tonale" },
  ],
  audi: [
    { id: "a1", name: "A1" },
    { id: "a3", name: "A3" },
    { id: "a4", name: "A4" },
    { id: "a5", name: "A5" },
    { id: "a6", name: "A6" },
    { id: "a7", name: "A7" },
    { id: "a8", name: "A8" },
    { id: "e-tron", name: "e-tron" },
    { id: "e-tron-gt", name: "e-tron GT" },
    { id: "q2", name: "Q2" },
    { id: "q3", name: "Q3" },
    { id: "q4-e-tron", name: "Q4 e-tron" },
    { id: "q5", name: "Q5" },
    { id: "q6-e-tron", name: "Q6 e-tron" },
    { id: "q7", name: "Q7" },
    { id: "q8", name: "Q8" },
    { id: "q8-e-tron", name: "Q8 e-tron" },
    { id: "rs3", name: "RS 3" },
    { id: "rs4", name: "RS 4" },
    { id: "rs5", name: "RS 5" },
    { id: "rs6", name: "RS 6" },
    { id: "rs7", name: "RS 7" },
    { id: "rs-e-tron-gt", name: "RS e-tron GT" },
    { id: "s3", name: "S3" },
    { id: "s4", name: "S4" },
    { id: "s5", name: "S5" },
    { id: "tt", name: "TT" },
  ],
  bmw: [
    { id: "1er", name: "1er", nameEn: "1 Series" },
    { id: "2er", name: "2er", nameEn: "2 Series" },
    { id: "2er-active-tourer", name: "2er Active Tourer", nameEn: "2 Series Active Tourer" },
    { id: "2er-gran-coupe", name: "2er Gran Coupé", nameEn: "2 Series Gran Coupé" },
    { id: "3er", name: "3er", nameEn: "3 Series" },
    { id: "4er", name: "4er", nameEn: "4 Series" },
    { id: "4er-gran-coupe", name: "4er Gran Coupé", nameEn: "4 Series Gran Coupé" },
    { id: "5er", name: "5er", nameEn: "5 Series" },
    { id: "7er", name: "7er", nameEn: "7 Series" },
    { id: "8er", name: "8er", nameEn: "8 Series" },
    { id: "i4", name: "i4" },
    { id: "i5", name: "i5" },
    { id: "i7", name: "i7" },
    { id: "ix", name: "iX" },
    { id: "ix1", name: "iX1" },
    { id: "ix2", name: "iX2" },
    { id: "ix3", name: "iX3" },
    { id: "m2", name: "M2" },
    { id: "m3", name: "M3" },
    { id: "m4", name: "M4" },
    { id: "m5", name: "M5" },
    { id: "x1", name: "X1" },
    { id: "x2", name: "X2" },
    { id: "x3", name: "X3" },
    { id: "x4", name: "X4" },
    { id: "x5", name: "X5" },
    { id: "x6", name: "X6" },
    { id: "x7", name: "X7" },
    { id: "xm", name: "XM" },
    { id: "z4", name: "Z4" },
  ],
  citroen: [
    { id: "berlingo", name: "Berlingo" },
    { id: "c3", name: "C3" },
    { id: "c3-aircross", name: "C3 Aircross" },
    { id: "c4", name: "C4" },
    { id: "c4-x", name: "C4 X" },
    { id: "c5-aircross", name: "C5 Aircross" },
    { id: "c5-x", name: "C5 X" },
    { id: "e-berlingo", name: "ë-Berlingo" },
    { id: "e-c3", name: "ë-C3" },
    { id: "e-c4", name: "ë-C4" },
    { id: "e-c4-x", name: "ë-C4 X" },
    { id: "spacetourer", name: "SpaceTourer" },
  ],
  cupra: [
    { id: "ateca", name: "Ateca" },
    { id: "born", name: "Born" },
    { id: "formentor", name: "Formentor" },
    { id: "leon", name: "Leon" },
    { id: "tavascan", name: "Tavascan" },
    { id: "terramar", name: "Terramar" },
  ],
  dacia: [
    { id: "duster", name: "Duster" },
    { id: "jogger", name: "Jogger" },
    { id: "sandero", name: "Sandero" },
    { id: "sandero-stepway", name: "Sandero Stepway" },
    { id: "spring", name: "Spring Electric" },
  ],
  fiat: [
    { id: "500", name: "500" },
    { id: "500e", name: "500e" },
    { id: "500x", name: "500X" },
    { id: "600e", name: "600e" },
    { id: "doblo", name: "Doblò" },
    { id: "ducato", name: "Ducato" },
    { id: "panda", name: "Panda" },
    { id: "tipo", name: "Tipo" },
  ],
  ford: [
    { id: "bronco", name: "Bronco" },
    { id: "explorer", name: "Explorer" },
    { id: "explorer-ev", name: "Explorer Electric" },
    { id: "fiesta", name: "Fiesta" },
    { id: "focus", name: "Focus" },
    { id: "galaxy", name: "Galaxy" },
    { id: "kuga", name: "Kuga" },
    { id: "mondeo", name: "Mondeo" },
    { id: "mustang", name: "Mustang" },
    { id: "mustang-mach-e", name: "Mustang Mach-E" },
    { id: "puma", name: "Puma" },
    { id: "ranger", name: "Ranger" },
    { id: "s-max", name: "S-MAX" },
    { id: "tourneo-connect", name: "Tourneo Connect" },
    { id: "tourneo-courier", name: "Tourneo Courier" },
    { id: "transit", name: "Transit" },
    { id: "transit-custom", name: "Transit Custom" },
  ],
  honda: [
    { id: "civic", name: "Civic" },
    { id: "cr-v", name: "CR-V" },
    { id: "e-ny1", name: "e:Ny1" },
    { id: "hr-v", name: "HR-V" },
    { id: "jazz", name: "Jazz" },
    { id: "zr-v", name: "ZR-V" },
  ],
  hyundai: [
    { id: "bayon", name: "Bayon" },
    { id: "i10", name: "i10" },
    { id: "i20", name: "i20" },
    { id: "i30", name: "i30" },
    { id: "ioniq-5", name: "IONIQ 5" },
    { id: "ioniq-6", name: "IONIQ 6" },
    { id: "kona", name: "Kona" },
    { id: "kona-ev", name: "Kona Elektro", nameEn: "Kona Electric" },
    { id: "nexo", name: "Nexo" },
    { id: "santa-fe", name: "Santa Fe" },
    { id: "staria", name: "Staria" },
    { id: "tucson", name: "Tucson" },
  ],
  jeep: [
    { id: "avenger", name: "Avenger" },
    { id: "compass", name: "Compass" },
    { id: "renegade", name: "Renegade" },
    { id: "wrangler", name: "Wrangler" },
  ],
  kia: [
    { id: "ceed", name: "Ceed" },
    { id: "ev3", name: "EV3" },
    { id: "ev6", name: "EV6" },
    { id: "ev9", name: "EV9" },
    { id: "niro", name: "Niro" },
    { id: "niro-ev", name: "Niro EV" },
    { id: "picanto", name: "Picanto" },
    { id: "proceed", name: "ProCeed" },
    { id: "sorento", name: "Sorento" },
    { id: "sportage", name: "Sportage" },
    { id: "stonic", name: "Stonic" },
    { id: "xceed", name: "XCeed" },
  ],
  landrover: [
    { id: "defender", name: "Defender" },
    { id: "discovery", name: "Discovery" },
    { id: "discovery-sport", name: "Discovery Sport" },
    { id: "range-rover", name: "Range Rover" },
    { id: "range-rover-evoque", name: "Range Rover Evoque" },
    { id: "range-rover-sport", name: "Range Rover Sport" },
    { id: "range-rover-velar", name: "Range Rover Velar" },
  ],
  mazda: [
    { id: "cx-3", name: "CX-3" },
    { id: "cx-30", name: "CX-30" },
    { id: "cx-5", name: "CX-5" },
    { id: "cx-60", name: "CX-60" },
    { id: "cx-80", name: "CX-80" },
    { id: "mazda2", name: "Mazda2" },
    { id: "mazda2-hybrid", name: "Mazda2 Hybrid" },
    { id: "mazda3", name: "Mazda3" },
    { id: "mazda6", name: "Mazda6" },
    { id: "mx-5", name: "MX-5" },
    { id: "mx-30", name: "MX-30" },
  ],
  mercedes: [
    { id: "a-klasse", name: "A-Klasse", nameEn: "A-Class" },
    { id: "amg-gt", name: "AMG GT" },
    { id: "b-klasse", name: "B-Klasse", nameEn: "B-Class" },
    { id: "c-klasse", name: "C-Klasse", nameEn: "C-Class" },
    { id: "cla", name: "CLA" },
    { id: "cle", name: "CLE" },
    { id: "cls", name: "CLS" },
    { id: "e-klasse", name: "E-Klasse", nameEn: "E-Class" },
    { id: "eqa", name: "EQA" },
    { id: "eqb", name: "EQB" },
    { id: "eqc", name: "EQC" },
    { id: "eqe", name: "EQE" },
    { id: "eqe-suv", name: "EQE SUV" },
    { id: "eqs", name: "EQS" },
    { id: "eqs-suv", name: "EQS SUV" },
    { id: "eqt", name: "EQT" },
    { id: "eqv", name: "EQV" },
    { id: "g-klasse", name: "G-Klasse", nameEn: "G-Class" },
    { id: "gla", name: "GLA" },
    { id: "glb", name: "GLB" },
    { id: "glc", name: "GLC" },
    { id: "glc-coupe", name: "GLC Coupé" },
    { id: "gle", name: "GLE" },
    { id: "gle-coupe", name: "GLE Coupé" },
    { id: "gls", name: "GLS" },
    { id: "s-klasse", name: "S-Klasse", nameEn: "S-Class" },
    { id: "sl", name: "SL" },
    { id: "sprinter", name: "Sprinter" },
    { id: "t-klasse", name: "T-Klasse", nameEn: "T-Class" },
    { id: "v-klasse", name: "V-Klasse", nameEn: "V-Class" },
    { id: "vito", name: "Vito" },
  ],
  mg: [
    { id: "mg4", name: "MG4 Electric" },
    { id: "mg5", name: "MG5 Electric" },
    { id: "marvel-r", name: "Marvel R" },
    { id: "zs", name: "ZS" },
    { id: "zs-ev", name: "ZS EV" },
  ],
  mini: [
    { id: "aceman", name: "Aceman" },
    { id: "clubman", name: "Clubman" },
    { id: "cooper", name: "Cooper" },
    { id: "cooper-se", name: "Cooper SE" },
    { id: "countryman", name: "Countryman" },
    { id: "john-cooper-works", name: "John Cooper Works" },
  ],
  nissan: [
    { id: "ariya", name: "Ariya" },
    { id: "juke", name: "Juke" },
    { id: "leaf", name: "Leaf" },
    { id: "micra", name: "Micra" },
    { id: "navara", name: "Navara" },
    { id: "qashqai", name: "Qashqai" },
    { id: "townstar", name: "Townstar" },
    { id: "x-trail", name: "X-Trail" },
  ],
  opel: [
    { id: "astra", name: "Astra" },
    { id: "astra-electric", name: "Astra Electric" },
    { id: "combo", name: "Combo" },
    { id: "corsa", name: "Corsa" },
    { id: "corsa-electric", name: "Corsa Electric" },
    { id: "crossland", name: "Crossland" },
    { id: "frontera", name: "Frontera" },
    { id: "grandland", name: "Grandland" },
    { id: "grandland-electric", name: "Grandland Electric" },
    { id: "insignia", name: "Insignia" },
    { id: "mokka", name: "Mokka" },
    { id: "mokka-electric", name: "Mokka Electric" },
    { id: "movano", name: "Movano" },
    { id: "rocks", name: "Rocks Electric" },
    { id: "vivaro", name: "Vivaro" },
    { id: "zafira", name: "Zafira Life" },
  ],
  peugeot: [
    { id: "108", name: "108" },
    { id: "208", name: "208" },
    { id: "308", name: "308" },
    { id: "408", name: "408" },
    { id: "508", name: "508" },
    { id: "2008", name: "2008" },
    { id: "3008", name: "3008" },
    { id: "5008", name: "5008" },
    { id: "e-208", name: "e-208" },
    { id: "e-308", name: "e-308" },
    { id: "e-2008", name: "e-2008" },
    { id: "e-3008", name: "e-3008" },
    { id: "e-5008", name: "e-5008" },
    { id: "partner", name: "Partner" },
    { id: "rifter", name: "Rifter" },
    { id: "traveller", name: "Traveller" },
  ],
  polestar: [
    { id: "polestar-2", name: "Polestar 2" },
    { id: "polestar-3", name: "Polestar 3" },
    { id: "polestar-4", name: "Polestar 4" },
  ],
  porsche: [
    { id: "718-boxster", name: "718 Boxster" },
    { id: "718-cayman", name: "718 Cayman" },
    { id: "911", name: "911" },
    { id: "cayenne", name: "Cayenne" },
    { id: "cayenne-coupe", name: "Cayenne Coupé" },
    { id: "macan", name: "Macan" },
    { id: "macan-electric", name: "Macan Electric" },
    { id: "panamera", name: "Panamera" },
    { id: "taycan", name: "Taycan" },
    { id: "taycan-cross-turismo", name: "Taycan Cross Turismo" },
    { id: "taycan-sport-turismo", name: "Taycan Sport Turismo" },
  ],
  renault: [
    { id: "arkana", name: "Arkana" },
    { id: "austral", name: "Austral" },
    { id: "captur", name: "Captur" },
    { id: "clio", name: "Clio" },
    { id: "espace", name: "Espace" },
    { id: "kangoo", name: "Kangoo" },
    { id: "megane", name: "Mégane" },
    { id: "megane-e-tech", name: "Mégane E-Tech Electric" },
    { id: "rafale", name: "Rafale" },
    { id: "scenic-e-tech", name: "Scénic E-Tech Electric" },
    { id: "twingo", name: "Twingo" },
    { id: "zoe", name: "ZOE" },
  ],
  seat: [
    { id: "arona", name: "Arona" },
    { id: "ateca", name: "Ateca" },
    { id: "ibiza", name: "Ibiza" },
    { id: "leon", name: "Leon" },
    { id: "tarraco", name: "Tarraco" },
  ],
  skoda: [
    { id: "elroq", name: "Elroq" },
    { id: "enyaq", name: "Enyaq" },
    { id: "enyaq-coupe", name: "Enyaq Coupé" },
    { id: "fabia", name: "Fabia" },
    { id: "kamiq", name: "Kamiq" },
    { id: "karoq", name: "Karoq" },
    { id: "kodiaq", name: "Kodiaq" },
    { id: "octavia", name: "Octavia" },
    { id: "scala", name: "Scala" },
    { id: "superb", name: "Superb" },
  ],
  smart: [
    { id: "eq-fortwo", name: "EQ fortwo" },
    { id: "eq-forfour", name: "EQ forfour" },
    { id: "hashtag-1", name: "#1" },
    { id: "hashtag-3", name: "#3" },
    { id: "hashtag-5", name: "#5" },
  ],
  suzuki: [
    { id: "across", name: "Across" },
    { id: "ignis", name: "Ignis" },
    { id: "jimny", name: "Jimny" },
    { id: "s-cross", name: "S-Cross" },
    { id: "swace", name: "Swace" },
    { id: "swift", name: "Swift" },
    { id: "vitara", name: "Vitara" },
  ],
  tesla: [
    { id: "model-3", name: "Model 3" },
    { id: "model-s", name: "Model S" },
    { id: "model-x", name: "Model X" },
    { id: "model-y", name: "Model Y" },
  ],
  toyota: [
    { id: "aygo-x", name: "Aygo X" },
    { id: "bz4x", name: "bZ4X" },
    { id: "c-hr", name: "C-HR" },
    { id: "camry", name: "Camry" },
    { id: "corolla", name: "Corolla" },
    { id: "corolla-cross", name: "Corolla Cross" },
    { id: "gr86", name: "GR86" },
    { id: "gr-supra", name: "GR Supra" },
    { id: "highlander", name: "Highlander" },
    { id: "hilux", name: "Hilux" },
    { id: "land-cruiser", name: "Land Cruiser" },
    { id: "mirai", name: "Mirai" },
    { id: "proace", name: "Proace" },
    { id: "proace-city", name: "Proace City" },
    { id: "rav4", name: "RAV4" },
    { id: "yaris", name: "Yaris" },
    { id: "yaris-cross", name: "Yaris Cross" },
  ],
  volvo: [
    { id: "c40", name: "C40 Recharge" },
    { id: "ec40", name: "EC40" },
    { id: "em90", name: "EM90" },
    { id: "ex30", name: "EX30" },
    { id: "ex40", name: "EX40" },
    { id: "ex90", name: "EX90" },
    { id: "s60", name: "S60" },
    { id: "s90", name: "S90" },
    { id: "v60", name: "V60" },
    { id: "v60-cross-country", name: "V60 Cross Country" },
    { id: "v90", name: "V90" },
    { id: "v90-cross-country", name: "V90 Cross Country" },
    { id: "xc40", name: "XC40" },
    { id: "xc60", name: "XC60" },
    { id: "xc90", name: "XC90" },
  ],
  vw: [
    { id: "arteon", name: "Arteon" },
    { id: "caddy", name: "Caddy" },
    { id: "golf", name: "Golf" },
    { id: "id3", name: "ID.3" },
    { id: "id4", name: "ID.4" },
    { id: "id5", name: "ID.5" },
    { id: "id7", name: "ID.7" },
    { id: "idbuzz", name: "ID. Buzz" },
    { id: "multivan", name: "Multivan" },
    { id: "passat", name: "Passat" },
    { id: "polo", name: "Polo" },
    { id: "taigo", name: "Taigo" },
    { id: "t-cross", name: "T-Cross" },
    { id: "tiguan", name: "Tiguan" },
    { id: "touareg", name: "Touareg" },
    { id: "touran", name: "Touran" },
    { id: "t-roc", name: "T-Roc" },
    { id: "transporter", name: "Transporter" },
    { id: "up", name: "up!" },
  ],
};

/**
 * Resolve brand/model IDs to display names.
 * Handles lowercase IDs from the backend (e.g. "audi" → "Audi", "a6" → "A6").
 */
export function resolveVehicleDisplay(brandId: string, modelId: string) {
  const brand = VEHICLE_BRANDS.find(
    (b) => b.id === brandId.toLowerCase() || b.name.toLowerCase() === brandId.toLowerCase()
  );
  const brandName = brand?.name ?? brandId;
  const brandLogo = brand?.logo;

  const models = VEHICLE_MODELS[brandId.toLowerCase()] ?? [];
  const model = models.find(
    (m) => m.id === modelId.toLowerCase() || m.name.toLowerCase() === modelId.toLowerCase()
  );
  const modelName = model?.name ?? modelId;

  return { brandName, modelName, brandLogo, modelNameEn: model?.nameEn };
}
