export interface VehicleBrand {
  id: string;
  name: string;
  logo?: string;
}

export interface VehicleModel {
  id: string;
  name: string;
}

/**
 * Common vehicle brands on the German market, sorted alphabetically.
 */
export const VEHICLE_BRANDS: VehicleBrand[] = [
  { id: "audi", name: "Audi", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/200px-Audi-Logo_2016.svg.png" },
  { id: "bmw", name: "BMW", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/200px-BMW.svg.png" },
  { id: "citroen", name: "Citroën" },
  { id: "cupra", name: "CUPRA" },
  { id: "fiat", name: "Fiat" },
  { id: "ford", name: "Ford", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Ford_logo_flat.svg/200px-Ford_logo_flat.svg.png" },
  { id: "hyundai", name: "Hyundai" },
  { id: "kia", name: "Kia" },
  { id: "mazda", name: "Mazda" },
  { id: "mercedes", name: "Mercedes-Benz", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/200px-Mercedes-Logo.svg.png" },
  { id: "mini", name: "MINI" },
  { id: "opel", name: "Opel", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Opel_logo_2024.svg/200px-Opel_logo_2024.svg.png" },
  { id: "peugeot", name: "Peugeot" },
  { id: "porsche", name: "Porsche", logo: "https://upload.wikimedia.org/wikipedia/de/thumb/6/60/Porsche_Logo.svg/200px-Porsche_Logo.svg.png" },
  { id: "renault", name: "Renault" },
  { id: "seat", name: "SEAT" },
  { id: "skoda", name: "Škoda" },
  { id: "tesla", name: "Tesla" },
  { id: "toyota", name: "Toyota", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Toyota.svg/200px-Toyota.svg.png" },
  { id: "vw", name: "Volkswagen", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Volkswagen_logo_2019.svg/200px-Volkswagen_logo_2019.svg.png" },
  { id: "volvo", name: "Volvo" },
];

/**
 * Real models per brand. Keys match VehicleBrand.id.
 */
export const VEHICLE_MODELS: Record<string, VehicleModel[]> = {
  audi: [
    { id: "a1", name: "A1" },
    { id: "a3", name: "A3" },
    { id: "a4", name: "A4" },
    { id: "a5", name: "A5" },
    { id: "a6", name: "A6" },
    { id: "q2", name: "Q2" },
    { id: "q3", name: "Q3" },
    { id: "q5", name: "Q5" },
    { id: "q7", name: "Q7" },
    { id: "e-tron", name: "e-tron" },
    { id: "tt", name: "TT" },
  ],
  bmw: [
    { id: "1er", name: "1er" },
    { id: "2er", name: "2er" },
    { id: "3er", name: "3er" },
    { id: "4er", name: "4er" },
    { id: "5er", name: "5er" },
    { id: "x1", name: "X1" },
    { id: "x3", name: "X3" },
    { id: "x5", name: "X5" },
    { id: "ix", name: "iX" },
    { id: "i4", name: "i4" },
    { id: "z4", name: "Z4" },
  ],
  citroen: [
    { id: "c3", name: "C3" },
    { id: "c4", name: "C4" },
    { id: "c5-aircross", name: "C5 Aircross" },
    { id: "berlingo", name: "Berlingo" },
    { id: "e-c4", name: "ë-C4" },
  ],
  cupra: [
    { id: "formentor", name: "Formentor" },
    { id: "born", name: "Born" },
    { id: "leon", name: "Leon" },
    { id: "ateca", name: "Ateca" },
  ],
  fiat: [
    { id: "500", name: "500" },
    { id: "500e", name: "500e" },
    { id: "500x", name: "500X" },
    { id: "panda", name: "Panda" },
    { id: "tipo", name: "Tipo" },
    { id: "ducato", name: "Ducato" },
  ],
  ford: [
    { id: "focus", name: "Focus" },
    { id: "fiesta", name: "Fiesta" },
    { id: "puma", name: "Puma" },
    { id: "kuga", name: "Kuga" },
    { id: "mustang-mach-e", name: "Mustang Mach-E" },
    { id: "explorer", name: "Explorer" },
    { id: "mondeo", name: "Mondeo" },
  ],
  hyundai: [
    { id: "i10", name: "i10" },
    { id: "i20", name: "i20" },
    { id: "i30", name: "i30" },
    { id: "tucson", name: "Tucson" },
    { id: "kona", name: "Kona" },
    { id: "ioniq-5", name: "IONIQ 5" },
    { id: "santa-fe", name: "Santa Fe" },
    { id: "bayon", name: "Bayon" },
  ],
  kia: [
    { id: "ceed", name: "Ceed" },
    { id: "sportage", name: "Sportage" },
    { id: "niro", name: "Niro" },
    { id: "ev6", name: "EV6" },
    { id: "stonic", name: "Stonic" },
    { id: "picanto", name: "Picanto" },
    { id: "sorento", name: "Sorento" },
  ],
  mazda: [
    { id: "cx-5", name: "CX-5" },
    { id: "cx-30", name: "CX-30" },
    { id: "mazda3", name: "Mazda3" },
    { id: "mazda2", name: "Mazda2" },
    { id: "mx-5", name: "MX-5" },
    { id: "cx-60", name: "CX-60" },
  ],
  mercedes: [
    { id: "a-klasse", name: "A-Klasse" },
    { id: "b-klasse", name: "B-Klasse" },
    { id: "c-klasse", name: "C-Klasse" },
    { id: "e-klasse", name: "E-Klasse" },
    { id: "gla", name: "GLA" },
    { id: "glb", name: "GLB" },
    { id: "glc", name: "GLC" },
    { id: "gle", name: "GLE" },
    { id: "cla", name: "CLA" },
    { id: "eqa", name: "EQA" },
    { id: "eqc", name: "EQC" },
  ],
  mini: [
    { id: "cooper", name: "Cooper" },
    { id: "countryman", name: "Countryman" },
    { id: "clubman", name: "Clubman" },
  ],
  opel: [
    { id: "astra", name: "Astra" },
    { id: "corsa", name: "Corsa" },
    { id: "mokka", name: "Mokka" },
    { id: "crossland", name: "Crossland" },
    { id: "grandland", name: "Grandland" },
    { id: "insignia", name: "Insignia" },
    { id: "combo", name: "Combo" },
  ],
  peugeot: [
    { id: "208", name: "208" },
    { id: "308", name: "308" },
    { id: "2008", name: "2008" },
    { id: "3008", name: "3008" },
    { id: "5008", name: "5008" },
    { id: "e-208", name: "e-208" },
    { id: "partner", name: "Partner" },
  ],
  porsche: [
    { id: "911", name: "911" },
    { id: "cayenne", name: "Cayenne" },
    { id: "macan", name: "Macan" },
    { id: "panamera", name: "Panamera" },
    { id: "taycan", name: "Taycan" },
    { id: "718", name: "718" },
  ],
  renault: [
    { id: "clio", name: "Clio" },
    { id: "captur", name: "Captur" },
    { id: "megane", name: "Mégane" },
    { id: "kadjar", name: "Kadjar" },
    { id: "austral", name: "Austral" },
    { id: "zoe", name: "ZOE" },
    { id: "arkana", name: "Arkana" },
  ],
  seat: [
    { id: "leon", name: "Leon" },
    { id: "ibiza", name: "Ibiza" },
    { id: "ateca", name: "Ateca" },
    { id: "arona", name: "Arona" },
  ],
  skoda: [
    { id: "octavia", name: "Octavia" },
    { id: "fabia", name: "Fabia" },
    { id: "superb", name: "Superb" },
    { id: "karoq", name: "Karoq" },
    { id: "kodiaq", name: "Kodiaq" },
    { id: "kamiq", name: "Kamiq" },
    { id: "scala", name: "Scala" },
    { id: "enyaq", name: "Enyaq" },
  ],
  tesla: [
    { id: "model-3", name: "Model 3" },
    { id: "model-y", name: "Model Y" },
    { id: "model-s", name: "Model S" },
    { id: "model-x", name: "Model X" },
  ],
  toyota: [
    { id: "yaris", name: "Yaris" },
    { id: "corolla", name: "Corolla" },
    { id: "rav4", name: "RAV4" },
    { id: "c-hr", name: "C-HR" },
    { id: "aygo-x", name: "Aygo X" },
    { id: "camry", name: "Camry" },
    { id: "supra", name: "Supra" },
    { id: "bz4x", name: "bZ4X" },
  ],
  vw: [
    { id: "golf", name: "Golf" },
    { id: "polo", name: "Polo" },
    { id: "passat", name: "Passat" },
    { id: "tiguan", name: "Tiguan" },
    { id: "t-roc", name: "T-Roc" },
    { id: "id3", name: "ID.3" },
    { id: "id4", name: "ID.4" },
    { id: "touran", name: "Touran" },
    { id: "t-cross", name: "T-Cross" },
    { id: "arteon", name: "Arteon" },
    { id: "up", name: "Up" },
  ],
  volvo: [
    { id: "xc40", name: "XC40" },
    { id: "xc60", name: "XC60" },
    { id: "xc90", name: "XC90" },
    { id: "v60", name: "V60" },
    { id: "s60", name: "S60" },
    { id: "c40", name: "C40" },
    { id: "ex30", name: "EX30" },
  ],
};
