# ---------------------------------------------------------------------------
# Template: Build and push a Docker image via ACR Tasks
# ---------------------------------------------------------------------------
# Uses `az acr build` to build remotely — no Docker daemon needed on the agent.
# ---------------------------------------------------------------------------
parameters:
  - name: imageName
    type: string
    displayName: 'Image name (without registry prefix)'

  - name: buildContext
    type: string
    displayName: 'Docker build context directory'

  - name: buildArgs
    type: string
    default: ''
    displayName: 'Optional --build-arg flags (e.g. --build-arg KEY=VALUE)'

steps:
  - task: AzureCLI@2
    displayName: 'ACR Build: ${{ parameters.imageName }}:$(Build.BuildId)'
    inputs:
      azureSubscription: 'Azure-B2C-PoC'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -euo pipefail
        az acr build \
          --registry crb2cpoc \
          --image "${{ parameters.imageName }}:$(Build.BuildId)" \
          --image "${{ parameters.imageName }}:latest" \
          ${{ parameters.buildArgs }} \
          "${{ parameters.buildContext }}"
